# Feito por: Gabriel dos Santos Sereno

## Maquina Linear

In [78]:
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import OneHotEncoder

## Exemplo 2.9

### Valores X e y

In [79]:
X = np.array([[1,1], [2,3], [3, 1], [4,4], [2,3], [4,4], [6,1], [7,7], [6,3], [10, 10]])
y = np.array([8.00, 16.66, 14.64, 23.93, 18.99, 24.76, 19.12, 39.56, 28.36, 53.69])

### Monte a matriz de dados X de dimensão n×m, colocando na i-ésima linha a i-ésima entrada em forma transposta xi.T;

In [80]:
# X transposto e seu shape
print(X.T)
print(X.T.shape)

[[ 1  2  3  4  2  4  6  7  6 10]
 [ 1  3  1  4  3  4  1  7  3 10]]
(2, 10)


### Monte a matriz de saídas desejadas Y de dimensão n×c, colocando na i-ésima linha a i-ésima saída em forma transposta yi.T;

In [81]:
# y transposto e seu shape
print(y.T)
print(y.T.shape)

[ 8.   16.66 14.64 23.93 18.99 24.76 19.12 39.56 28.36 53.69]
(10,)


### Insere na matriz de dados X, antes da primeira coluna, uma coluna com o valor fixo 1 em cada linha, criando assim a matriz de dados aumentada X ̃ = [1 X] de dimensão n×(m+1);

In [82]:
xTil = np.append(np.ones([10,1]), X, axis=1)

print(xTil.T)
print(xTil.shape)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  2.  3.  4.  2.  4.  6.  7.  6. 10.]
 [ 1.  3.  1.  4.  3.  4.  1.  7.  3. 10.]]
(10, 3)


### Calcule a pseudoinversa X ̃ † de dimensão (m+1)×n da matriz de dados aumentada conforme a (eq. 2.62);

In [83]:
xInverse = np.linalg.pinv(xTil)

print(xInverse)
print(xInverse.shape)

[[ 0.32959726  0.25921353  0.20440729  0.13012918  0.25921353  0.13012918
   0.01662234 -0.06933891  0.00883359 -0.26880699]
 [-0.05328647 -0.06986132  0.01709726 -0.02536094 -0.06986132 -0.02536094
   0.12267287  0.00256459  0.07090616  0.03049012]
 [ 0.00275456  0.04193579 -0.04901216  0.02270137  0.04193579  0.02270137
  -0.12666223  0.04264818 -0.06159764  0.06259498]]
(3, 10)


### Multiplique a pseudoinversa X ̃ † de dimensão (m+1)×n pela matriz de saídas desejadas Y de dimensão n×c, resultando na matriz de pesos W de dimensão (m+1)×c, W = X ̃ †Y

In [84]:
result = xInverse.dot(y.T)

print(result)

[4.59929806 2.19350541 2.78403448]


## Exemplo 2.11

In [85]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

onehot = OneHotEncoder()
yonehot = onehot.fit_transform(y.reshape(-1, 1)).todense()

### Monte a matriz de dados X de dimensão n×m, colocando na i-ésima linha a i-ésima entrada em forma transposta xi.T;

In [86]:
# X transposto e seu shape
print(X.T.shape)
print(X.T)

(4, 150)
[[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
  5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
  5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
  6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
  6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
  5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
  6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
  6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
  6.7 6.7 6.3 6.5 6.2 5.9]
 [3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.  3.  4.  4.4 3.9 3.5
  3.8 3.8 3.4 3.7 3.6 3.3 3.4 3.  3.4 3.5 3.4 3.2 3.1 3.4 4.1 4.2 3.1 3.2
  3.5 3.6 3.  3.4 3.5 2.3 3.2 3.5 3.8 3.  3.8 3.2 3.7 3.3 3.2 3.2 3.1 2.3
  2.8 2.8 3.3 2.4 2.9 2.7 2.  3.  2.2 2.9 2.9 3.1 3.  2.7 2.2 2.5 3.2 2.8
  2.5 2.8 2.9 3.  2.8 3.  2.9 2.6 2.4 2.4 2.7 2.7 3.  3.4 3.1 2.3 3.  2.5
  2

### Monte a matriz de saídas desejadas Y de dimensão n×c, colocando na i-ésima linha a i-ésima saída em forma transposta yi.T;

In [87]:
print(yonehot.shape)
print(yonehot)

(150, 3)
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1.

### Insere na matriz de dados X, antes da primeira coluna, uma coluna com o valor fixo 1 em cada linha, criando assim a matriz de dados aumentada X ̃ = [1 X] de dimensão n×(m+1);

In [88]:
xTil = np.append(np.ones([150,1]), X, axis=1)

print(xTil.T)
print(xTil.shape)

[[1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1. ]
 [5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
  5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
  5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
  6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
  6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
  5.5 6.1 5.8 5.  5.

### Calcule a pseudoinversa X ̃ † de dimensão (m+1)×n da matriz de dados aumentada conforme a (eq. 2.62);

In [89]:
xInverse = np.linalg.pinv(xTil)

print(xInverse)
print(xInverse.shape)

[[-1.84381009e-02  4.59663834e-02  5.44112472e-02  7.85386552e-02
  -1.33312950e-02 -7.37102815e-02  5.80116807e-02  3.92055925e-03
   1.17949732e-01  3.55271450e-02 -7.06975367e-02  3.13860252e-02
   5.43483095e-02  1.13283861e-01 -1.50621876e-01 -1.54500621e-01
  -8.07852729e-02 -1.39716679e-02 -1.08980238e-01 -3.54275797e-02
  -4.39353813e-02 -2.32195935e-02  3.09871499e-02  1.57505480e-02
   3.66922688e-02  3.66555200e-02  1.46221730e-02 -2.95177121e-02
  -2.35449067e-02  5.97174908e-02  5.46106849e-02 -3.85400111e-02
  -8.04334644e-02 -1.24022410e-01  3.99935780e-02  1.40974222e-02
  -7.16002850e-02 -4.94936894e-03  1.08439431e-01 -8.92779982e-03
  -2.89205670e-03  1.54248377e-01  9.29563244e-02  1.58134858e-02
  -2.38861554e-02  6.32811754e-02 -3.81252649e-02  6.90283541e-02
  -5.78491776e-02  9.89336463e-03 -1.27366389e-01 -4.93472973e-02
  -9.87725480e-02  1.18185308e-01 -2.94606956e-02  6.26245632e-02
  -3.62365628e-02  1.61753376e-01 -5.89834739e-02  1.28461858e-01
   1.83408

### Multiplique a pseudoinversa X ̃ † de dimensão (m+1)×n pela matriz de saídas desejadas Y de dimensão n×c, resultando na matriz de pesos W de dimensão (m+1)×c, W = X ̃ †Y

In [90]:
result = xInverse.dot(yonehot)

print(result)

[[ 0.11822289  1.57705897 -0.69528186]
 [ 0.06602977 -0.02015368 -0.04587608]
 [ 0.24284787 -0.44561626  0.20276839]
 [-0.22465712  0.22066921  0.00398791]
 [-0.05747273 -0.4943066   0.55177932]]


### Utilizando apenas as caracteristicas 3 e 4

In [91]:
X = iris.data[:, 2:]
xTil = np.append(np.ones([150,1]), X, axis=1)
xInverse = np.linalg.pinv(xTil)
result = xInverse.dot(yonehot)
aux = xTil[0]

print("Resultado:", result)
print("Primeira setosa:", aux.dot(result))

Resultado: [[ 1.26603335 -0.10584416 -0.16018919]
 [-0.25132905  0.32433516 -0.07300611]
 [ 0.00983426 -0.65008953  0.64025527]]
Primeira setosa: [[ 0.91613953  0.21820716 -0.13434669]]
